### ISSUE TITLE
Page builder not fully capture errors and it make page worker pending.

### ISSUE THREAD

**Issue by jwu** [fireball-x/fireball#134]
```
[80888] Compiled successfully
[80888:0720/200320:INFO:CONSOLE(15)] "running:", source: file:///Users/johnny/fireball/fireball/canvas-studio/static/general-worker.html (15)
[80888:0720/200320:INFO:CONSOLE(0)] "'webkitAudioContext' is deprecated. Please use 'AudioContext' instead.", source:  (0)
[80888:0720/200321:INFO:CONSOLE(129)] "Not yet implemented", source: /Users/johnny/fireball/fireball/editor-framework/page/editor-init.js (129)
[80888] Not yet implemented
[80888:0720/200321:INFO:CONSOLE(389)] "Uncaught TypeError: Cannot set property '_FB_wrapper' of null", source: /Users/johnny/fireball/fireball/engine-framework/src/runtime/wrappers/node.js (389)
[80888:0720/200321:INFO:CONSOLE(129)] "Not yet implemented", source: /Users/johnny/fireball/fireball/editor-framework/page/editor-init.js (129)
[80888] Not yet implemented
[80888:0720/200321:INFO:CONSOLE(389)] "Uncaught TypeError: Cannot set property '_FB_wrapper' of null", source: /Users/johnny/fireball/fireball/engine-framework/src/runtime/wrappers/node.js (389)
[80888:0720/200321:INFO:CONSOLE(129)] "Not yet implemented", source: /Users/johnny/fireball/fireball/editor-framework/page/editor-init.js (129)
[80888] Not yet implemented
[80888:0720/200321:INFO:CONSOLE(389)] "Uncaught TypeError: Cannot set property '_FB_wrapper' of null", source: /Users/johnny/fireball/fireball/engine-framework/src/runtime/wrappers/node.js (389)
[80888:0720/200325:WARNING:ipc_message_attachment_set.cc(37)] MessageAttachmentSet destroyed with unconsumed descriptors: 0/1
Failed to send "console:error" to worker because web contents not yet loaded
[80888] Uncaught Exception: Error: Object has been destroyed
    at Error (native)
    at EditorWindow.close (/Users/johnny/fireball/fireball/editor-framework/core/editor-window.js:233:20)
    at /Users/johnny/fireball/fireball/canvas-studio/core/gulp-build.js:130:36
    at EditorWindow.<anonymous> (/Users/johnny/fireball/fireball/editor-framework/core/editor-window.js:111:21)
    at emitOne (events.js:82:20)
    at BrowserWindow.emit (events.js:169:7)
```

**Comment by jwu** [comment]
This happens when page-level builder have error, after that it will not return error to core. So the page worker pending there until user close the App.

When editor app closed, it actually check all page-level pending ipcs, and force invoke callback, that's why we got reply at the end of the programme.
