### ISSUE TITLE
Problem with Pixi projects in Fireball release 0.5 alpha 2

### ISSUE THREAD

**Issue by abarra** [fireball-x/fireball#159]
Hi guys, 

I'm trying to test pixi projects with Fireball but it is not working for me. I'm getting this error

Initializing Runtime pixi
[10009] Uncaught Exception: Error: Cannot find module '/Applications/Fireball-0.5-alpha-2-mac.app/Contents/Resources/app/runtime/runtime-pixi'
    at Function.Module._resolveFilename (module.js:334:15)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at /Applications/Fireball-0.5-alpha-2-mac.app/Contents/Resources/app/canvas-studio/init.js:155:13
    at /Applications/Fireball-0.5-alpha-2-mac.app/Contents/Resources/app/node_modules/async/lib/async.js:699:13
    at iterate (/Applications/Fireball-0.5-alpha-2-mac.app/Contents/Resources/app/node_modules/async/lib/async.js:256:13)
    at /Applications/Fireball-0.5-alpha-2-mac.app/Contents/Resources/app/node_modules/async/lib/async.js:268:29
    at /Applications/Fireball-0.5-alpha-2-mac.app/Contents/Resources/app/node_modules/async/lib/async.js:40:16
    at /Applications/Fireball-0.5-alpha-2-mac.app/Contents/Resources/app/node_modules/async/lib/async.js:705:17

is it a known issue? could you help me?

**Comment by jwu** [comment]
Hi abarra,

This is a known issue. We will integrate Pixi after 0.5 final release. Please select cocos2d-js first. I will add 'coming soon' hinting text in Dashboard to notify people. Thank you for your feedback

**Comment by abarra** [comment]
Thanks!
