### ISSUE TITLE
Warning `Can not find source element by id` when moving assets in asset view.

### ISSUE THREAD

**Issue by nantas** [fireball-x/fireball#199]
```js
[27645:0812/144233:INFO:CONSOLE(141)] "Can not find source element by id: fd0f415b-57f3-4f2e-b3c7-8d34af21652f", source: /Users/nantas/projects/fireball-x/fireball/editor-framework/page/editor-init.js (141)
[27645] Warning: Can not find source element by id: fd0f415b-57f3-4f2e-b3c7-8d34af21652f
    at assets-search-result.Polymer.moveItemById (file:///Users/nantas/projects/fireball-x/fireball/builtin/assets/panel/assets-search-result.js:160:24)
    at file:///Users/nantas/projects/fireball-x/fireball/builtin/assets/panel/assets.js:240:30
    at Array.forEach (native)
    at file:///Users/nantas/projects/fireball-x/fireball/builtin/assets/panel/assets.js:239:19
    at Array.forEach (native)
    at editor-assets.Editor.registerPanel.asset-db:assets-moved (file:///Users/nantas/projects/fireball-x/fireball/builtin/assets/panel/assets.js:237:23)
    at EventEmitter.<anonymous> (/Users/nantas/projects/fireball-x/fireball/editor-framework/page/editor-panel.js:65:12)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/Users/nantas/projects/fireball-x/fireball/editor-framework/core/editor-init.js:169:52)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter._sendToCore (/Users/nantas/projects/fireball-x/fireball/editor-framework/core/ipc-init.js:40:25)
    at EventEmitter.<anonymous> (/Users/nantas/projects/fireball-x/fireball/editor-framework/core/ipc-init.js:50:24)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (/Users/nantas/projects/fireball-x/fireball/bin/electron/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:91:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

So far it doesn't seem to break anything..

**Comment by nantas** [comment]
Correct, after this warning and reload the scene file. All moved sprite reference is gone.
