### ISSUE TITLE
Need better error message when change parent of a node created in scene

### ISSUE THREAD

**Issue by nantas** [fireball-x/fireball#203]
When I change the parent of a node created in scene by `addChild(node)`, I got the following message:
```js
Error: The id already added in the tree: fe29aXWQT1GXZnHYaUO9k6v
    at hierarchy-tree.EditorUI.idtree.idtree.addItem (packages://ui-tree/widget/id-tree.js:34:23)
    at hierarchy-tree.<anonymous> (file:///Users/nantas/projects/fireball-x/fireball/builtin/hierarchy/panel/hierarchy-tree.js:722:22)
    at Array.forEach (native)
    at hierarchy-tree.Polymer._newEntryRecursively (file:///Users/nantas/projects/fireball-x/fireball/builtin/hierarchy/panel/hierarchy-tree.js:720:28)
    at hierarchy-tree.Polymer._applyCmds (file:///Users/nantas/projects/fireball-x/fireball/builtin/hierarchy/panel/hierarchy-tree.js:543:34)
    at hierarchy-tree.Polymer._updateSceneGraph (file:///Users/nantas/projects/fireball-x/fireball/builtin/hierarchy/panel/hierarchy-tree.js:682:22)
    at editor-hierarchy.Editor.registerPanel.scene:reply-query-hierarchy (file:///Users/nantas/projects/fireball-x/fireball/builtin/hierarchy/panel/hierarchy.js:165:21)
    at EventEmitter.<anonymous> (/Users/nantas/projects/fireball-x/fireball/editor-framework/page/editor-panel.js:65:12)
    at emitThree (events.js:97:13)
```

It's hard to tell from the error that I should use `removeFromParent` first before `addChild`. Please improve the error message.

**Comment by jwu** [comment]
@jareguo This is also hard for hierarchy tree to judge it.

**Comment by jwu** [comment]
duplicate with #202
