### ISSUE TITLE
input in "code editor" is doubled 

### ISSUE THREAD

**Issue by Coretool** [fireball-x/fireball#219]
Any kind of text input in the code editor gets doubled: 
If you want to write "hello world" you get hheelllloo wwoorrlldd ! 
Please fix the bug =)

**Comment by yorkie** [comment]
Hey @Coretool, may I ask you to print the log in code editor?

**Comment by Coretool** [comment]
```
TypeError: Cannot read property 'forEach' of undefined
    at getCompletions (packages://code-editor/panel/codemirror/addon/hint/javascript-hint.js:185:26)
    at scriptHint (packages://code-editor/panel/codemirror/addon/hint/javascript-hint.js:57:19)
    at Array.javascriptHint (packages://code-editor/panel/codemirror/addon/hint/javascript-hint.js:63:12)
    at Object.hint (packages://code-editor/panel/codemirror/addon/hint/show-hint.js:389:29)
    at Object.Completion._update (packages://code-editor/panel/codemirror/addon/hint/show-hint.js:128:33)
    at Object.Completion.update (packages://code-editor/panel/codemirror/addon/hint/show-hint.js:116:12)
    at packages://code-editor/panel/codemirror/addon/hint/show-hint.js:101:64
```
Looks like something is wrong with your foreach loop! =)

**Comment by yorkie** [comment]
Now the doubled inputs should be fixed at https://github.com/fireball-packages/code-editor/commit/1d0e4df48e9dee258613177cced7492bf30e1682. Thanks for your feedback ~

**Comment by jwu** [comment]
@yorkie is this fixed? can i close it?

**Comment by yorkie** [comment]
Yea, Fixed by adding a validation before the `forEach` call.
