### ISSUE TITLE
error when dragging node to inspector field

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#264]
场景里拖节点时偶尔会有报错，但报错后重新点开 inspector 又能看到节点已经正确赋值。
```
Failed to create field Runtime.NodeWrapper. Message: type not the same Runtime.SpriteWrapper:Runtime.NodeWrapper
    at editor-field.Editor.registerWidget._rebuild (packages://ui-property/widget/field/field.js:106:36)
    at editor-field.<anonymous> (packages://ui-property/widget/field/field.js:60:18)
    at Object.Debouncer.complete (app://bower_components/polymer/polymer.html:968:15)
    at EventEmitter.<anonymous> (/Users/jareguo/firebox/fireball/editor-framework/core/editor-init.js:170:54)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter._sendToCore (/Users/jareguo/firebox/fireball/editor-framework/core/ipc-init.js:40:25)
    at EventEmitter.<anonymous> (/Users/jareguo/firebox/fireball/editor-framework/core/ipc-init.js:50:24)
```

**Comment by jwu** [comment]
Hi, 我在最新版本里尝试重现这个问题但是没有重现出来, 有没有什么重现的方法或者 project ?
