### ISSUE TITLE
cannot have ccui.Button array property

### ISSUE THREAD

**Issue by nantas** [fireball-x/fireball#265]
```js
        myCCUIButtons: {
            default: [],
            type: [cc.Node]
        },
```

will result in following error when dragging a ccui.Button to one of the property field.

```js
Failed to create field Runtime.NodeWrapper. Message: type not the same Runtime.ButtonWrapper:Runtime.NodeWrapper
    at editor-field.Editor.registerWidget._rebuild (packages://ui-property/widget/field/field.js:106:36)
    at editor-field.<anonymous> (packages://ui-property/widget/field/field.js:60:18)
    at Object.Debouncer.complete (app://bower_components/polymer/polymer.html:986:15)
    at EventEmitter.<anonymous> (/Users/nantas/projects/fireball-x/fireball/editor-framework/core/editor-init.js:170:54)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
    at EventEmitter._sendToCore (/Users/nantas/projects/fireball-x/fireball/editor-framework/core/ipc-init.js:40:25)
    at EventEmitter.<anonymous> (/Users/nantas/projects/fireball-x/fireball/editor-framework/core/ipc-init.js:50:24)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
    at EventEmitter.<anonymous> (/Users/nantas/projects/fireball-x/fireball/bin/electron/Electron.app/Contents/Resources/atom.asar/browser/api/lib/web-contents.js:91:23)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```

**Comment by jareguo** [comment]
duplicated with #264

**Comment by jwu** [comment]
not exactly the same problem. Just fix it.
