### ISSUE TITLE
Jimp Error when texture is resized

### ISSUE THREAD

**Issue by nantas** [fireball-x/fireball#273]
```js
Uncaught Exception: Error: Invalid settings specified for the resizer.
    at Resize.initialize (/Users/nantas/projects/fireball-x/fireball/node_modules/jimp/resize.js:25:16)
    at new Resize (/Users/nantas/projects/fireball-x/fireball/node_modules/jimp/resize.js:17:10)
    at Jimp.resize (/Users/nantas/projects/fireball-x/fireball/node_modules/jimp/jimp.js:851:18)
    at /Users/nantas/projects/fireball-x/fireball/asset-db/lib/utils.js:302:19
    at fn (/Users/nantas/projects/fireball-x/fireball/node_modules/async/lib/async.js:717:34)
    at /Users/nantas/projects/fireball-x/fireball/node_modules/async/lib/async.js:1170:16
    at /Users/nantas/projects/fireball-x/fireball/node_modules/async/lib/async.js:172:37
    at /Users/nantas/projects/fireball-x/fireball/node_modules/async/lib/async.js:677:43
    at /Users/nantas/projects/fireball-x/fireball/node_modules/async/lib/async.js:173:37
    at Immediate._onImmediate (/Users/nantas/projects/fireball-x/fireball/node_modules/async/lib/async.js:1163:34)
```

When changed the size of a texture, Fireball can launch but the sprite size will not be updated. Once editor is closed, on next launch the above error will be poped.

**Comment by nantas** [comment]
On second test, I can confirm that the error happens when importing the following pngs:
![fengexian](https://cloud.githubusercontent.com/assets/344547/9853349/bf788bba-5b35-11e5-958f-30f158cab10a.png)
![zhuozi](https://cloud.githubusercontent.com/assets/344547/9853350/bfa10bd0-5b35-11e5-9435-d1477d861b7d.png)
