### ISSUE TITLE
make scene view smart enough to repaint on demand

### ISSUE THREAD

**Issue by jareguo** [fireball-x/fireball#96]
@jwu 请在场景需要重绘时（停止和暂停状态下），调用 `Fire.engine.repaintInEditMode()`，否则场景将不会刷新。
另外之前的 fastTick 和 slowTick 改成了 `Fire.engine.animatingInEditMode`，你需要在选中粒子时，设置 Fire.engine.animatingInEditMode = true，取消选中时设置 Fire.engine.animatingInEditMode = false

**Comment by jwu** [comment]
我调用了这个函数后, 会显示

```
Not yet implemented
9
    at NYI (/Users/johnny/fireball/fireball/engine-framework/src/runtime/wrappers/utils.js:5:14)
    at Fire.Class.tickInEditMode (/Users/johnny/fireball/fireball/engine-framework/src/runtime/wrappers/engine.js:222:18)
    at Fire.Class._tick (/Users/johnny/fireball/fireball/engine-framework/src/runtime/wrappers/engine.js:387:22)
```
